#!/bin/bash
# bootstrap.sh – prepare local OrbVis setup before `docker compose up`.
#
# Generates a .env file with a fresh random SECRET_KEY if none exists yet.
# Safe to run repeatedly; existing .env files are left untouched.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

ENV_FILE=".env"

if [[ -f "$ENV_FILE" ]]; then
  echo ".env already exists — leaving it untouched."
  exit 0
fi

if command -v openssl >/dev/null 2>&1; then
  SECRET_KEY="$(openssl rand -hex 32)"
elif command -v python3 >/dev/null 2>&1; then
  SECRET_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
else
  echo "Error: need either openssl or python3 to generate SECRET_KEY." >&2
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Auto-generated by bootstrap.sh — keep this file private (.gitignore'd).
# Re-run bootstrap.sh after deleting this file to mint a new SECRET_KEY.
SECRET_KEY=$SECRET_KEY
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE with a fresh SECRET_KEY."
